spring.application.name=Notifications

spring.datasource.url=jdbc:postgresql://hrmdb.c3ykgskuuzr8.ap-south-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=HrmAnasolDb

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8084


spring.cache.type=redis
spring.data.redis.sentinel.master=redis-master
spring.data.redis.sentinel.nodes=host.docker.internal:5000,host.docker.internal:5001,host.docker.internal:5002
spring.data.redis.password=RedisPasswordMaster
# logging.level.io.lettuce.core=DEBUG
# logging.level.org.springframework.data.redis=DEBUG


redis.stream.key=notifications
redis.stream.group=notification-group